"""Agregar unidad_medida a materiales

Revision ID: 06000aace817
Revises: 96c180341ead
Create Date: 2025-05-10 16:29:21.716092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06000aace817'
down_revision = '96c180341ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.String(length=20), nullable=False))
        batch_op.alter_column('cantidad_disponible',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('id_zona',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('materiales_id_zona_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'zonas_trabajo', ['id_zona'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('materiales_id_zona_fkey', 'zonas_trabajo', ['id_zona'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('id_zona',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cantidad_disponible',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('unidad_medida')

    # ### end Alembic commands ###
