"""Agregar unidad de medida a Solicitud

Revision ID: 4a61f5562802
Revises: 5bb4daac13b0
Create Date: 2025-05-25 21:15:57.467987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a61f5562802'
down_revision = '5bb4daac13b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_unidad', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unidades_medida', ['id_unidad'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_unidad')

    # ### end Alembic commands ###
