"""Agregar correción

Revision ID: a5c4b1ca7ce6
Revises: 4a61f5562802
Create Date: 2025-05-27 00:15:55.607652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c4b1ca7ce6'
down_revision = '4a61f5562802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_compra', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    with op.batch_alter_table('solicitudes_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_zona', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'zonas_trabajo', ['id_zona'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_zona')

    with op.batch_alter_table('orden_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
