"""Agregar atributo en modelo mensaje

Revision ID: c7036413125b
Revises: a5c4b1ca7ce6
Create Date: 2025-05-28 13:51:49.958048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7036413125b'
down_revision = 'a5c4b1ca7ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinatario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conversacion_id', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['destinatario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conversacion_id')
        batch_op.drop_column('destinatario_id')

    # ### end Alembic commands ###
