"""Agregar activo a materiales

Revision ID: ceb709d96060
Revises: c7036413125b
Create Date: 2025-05-28 14:26:15.857049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb709d96060'
down_revision = 'c7036413125b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
